### ISSUE TITLE
https issue in develop site

### ISSUE THREAD

**Issue by ryan7998** [UTBootCampGroup2/SaveTV#43]
Not able to connect to apis from github develop site
![https-issue](https://user-images.githubusercontent.com/4224443/105904734-7fbf5480-5fef-11eb-9fac-3ba35f20a73b.PNG)

Possible Solution: while fetching apis: lets try with https instead of http.
For example: fetch(**https:**//api.tvmaze.com/singlesearch/shows?q=) instead of fetch(**http:**//api.tvmaze.com/singlesearch/shows?q=)

**Comment by dfrancis-tech** [comment]
completed
