### ISSUE TITLE
[bug] please validate and correct your HTML and CSS code with validation tools

### ISSUE THREAD

**Issue by eapostol** [UTBootCampGroup2/SaveTV#85]
incorrectly leaving your HTML tags not properly closed, or having closed tags where there are no open tags may cause your web page to not render correctly. 

<img width="1086" alt="Screen Shot 2021-02-17 at 12 29 24 AM" src="https://user-images.githubusercontent.com/565104/108160506-34143e00-70b7-11eb-93c2-c611c1e10de9.png">

For example, in the above image, why is there an extra closed _italics_ tag `</i>` ?

It is recommended that you run your html code against such tools as  [HTML validator](https://validator.w3.org/) and [http://csslint.net/](http://csslint.net/) as required.

**Comment by dfrancis-tech** [comment]
completed
